# PID Control Parameters
# Units:
# Position: Kp [1/s]
# Velocity: Kp [N/(m/s)], Ki [N/(m)], Kd [N*s/m] (Note: Actually converts vel error to acceleration or force commands depending on impl)
# Attitude: Kp [1/s]
# Rate: Kp [Nm/(rad/s)], Ki [Nm/rad], Kd [Nm*s/rad]

position:
  kp: [8.0, 8.0, 12.0]
  output_limits: [-null, null]  # null represents infinity

velocity:
  kp: [4.0, 4.0, 6.0]
  ki: [0.0, 0.0, 0.0]
  kd: [0.05, 0.05, 0.05]
  output_limits: [-null, null]

attitude:
  kp: [9.0, 9.0, 12.0]
  output_limits: [-null, null]

rate:
  kp: [3.0, 3.0, 3.0]
  ki: [100.0, 100.0, 100.0]
  kd: [0.00005, 0.00005, 0.00005]
  output_limits: [-null, null]

mixer:
  Ct: 0.01343       # Motor thrust coefficient (N/krpm^2)
  Cd: 0.0003099     # Motor torque coefficient (Nm/krpm^2)
  arm_length: 0.18  # Arm length (m)
  max_thrust: 6.5   # Max thrust per motor (N)
  max_torque: 0.15  # Max torque per motor (Nm)
  max_rpm: 22.0     # Max RPM (krpm)

simulation:
  dt: 0.0001        # Simulation timestep (s)
  gravity: 9.81     # Gravity (m/s^2)
  mass: 1.27        # UAV Mass (kg)
