name: Quadrotor
mass: 1.27
inertia:
  Ixx: 0.022
  Iyy: 0.022
  Izz: 0.036
dimensions:
  arm_length: 0.18
  height: 0.05
  propeller_diameter: 0.1
motors:
  count: 4
  max_thrust: 6.5
  max_torque: 0.15
  max_speed: 22
  thrust_coefficient: 0.01343
  torque_coefficient: 0.0003099
  arm_length: 0.18
  layout: x
  motor_order:
  - 0
  - 1
  - 2
  - 3
  rotation_direction:
  - 1
  - -1
  - 1
  - -1
gravity: 9.81
drag_coefficient: 0.1
max_tilt_angle: 30.0
body_name: UAV_body
