position:
  frequency: 50
  pid:
    kp:
    - 8.0
    - 8.0
    - 12.0
    ki:
    - 0.0
    - 0.0
    - 0.0
    kd:
    - 0.0
    - 0.0
    - 0.0
    output_limit:
    - -5.0
    - 5.0
velocity:
  frequency: 50
  pid:
    kp:
    - 4.0
    - 4.0
    - 6.0
    ki:
    - 0.0
    - 0.0
    - 0.0
    kd:
    - 0.05
    - 0.05
    - 0.05
    output_limit:
    - -10.0
    - 10.0
attitude:
  frequency: 250
  pid:
    kp:
    - 9.0
    - 9.0
    - 12.0
    ki:
    - 0.0
    - 0.0
    - 0.0
    kd:
    - 0.0
    - 0.0
    - 0.0
    output_limit:
    - -5.0
    - 5.0
angle_rate:
  frequency: 1000
  pid:
    kp:
    - 3.0
    - 3.0
    - 3.0
    ki:
    - 100.0
    - 100.0
    - 100.0
    kd:
    - 5.0e-05
    - 5.0e-05
    - 5.0e-05
    output_limit:
    - -2.0
    - 2.0
mixer_type: standard
control_mode: attitude
enable_anti_windup: true
enable_feedforward: false
